baseURL = 'https://perpdex.com/'
languageCode = 'en-us'
title = 'PerpDEX'
theme = "ananke"
relativeURLs = true

[menu]
# [[menu.main]]
#   name = 'About Us'
#   weight = -120
[[menu.main]]
  name = 'Whitepaper'
  url = 'https://perpdex.com/pdfs/whitepaper.pdf'
  weight = -110
[[menu.main]]
  name = 'App (shibuya testnet)'
  url = 'https://bafybeiez4ms56555v6x2f2pipkmlwefhigkb66te3xl5xpg2mms7ie5mra.ipfs.infura-ipfs.io/'
  weight = -90
[[menu.main]]
  name = 'Docs'
  url = 'https://docs.perpdex.com/'
  weight = -80
# [[menu.main]]
#   name = 'Contact Us'
#   url = '#footer'
#   weight = -70

[params]
  favicon = "images/favicon/favicon.png"
  custom_css = ["css/override.css"]
  site_logo = "images/perpdex_logo_header.svg"
  site_logo_footer = "images/perpdex_logo_footer.svg"
  discord_url = "https://discord.gg/6gXs4qq9hy"
  twitter_url = "https://twitter.com/perpdex"
  medium_url = "https://medium.com/perpdex"
  docs_url = "https://docs.perpdex.com/"
  whitepaper_url = "https://perpdex.com/pdfs/whitepaper.pdf"
  testnet_url = "https://bafybeiez4ms56555v6x2f2pipkmlwefhigkb66te3xl5xpg2mms7ie5mra.ipfs.infura-ipfs.io/"
