baseURL = 'https://perpdex.com/'
languageCode = 'en-us'
title = 'PerpDEX'
theme = "ananke"
relativeURLs = true

[menu]
[[menu.main]]
  name = 'About Us'
  weight = -120
[[menu.main]]
  name = 'WhitePaper'
  url = 'https://perpdex.com/pdfs/whitepaper.pdf'
  weight = -110
# [[menu.main]]
#   name = 'Litepaper'
#   url = 'https://magnetic-holiday-dbf.notion.site/PerpDEX-Litepaper-acac35286f214b6db60dc64e58f42ca2'
#   weight = -100
[[menu.main]]
  name = 'App (rinkeby testnet)'
  url = 'https://ipfs.infura.io/ipfs/QmYLySzkqAQ9P4Kedu3TWBHxdFwdopD1YdBKimo2mSJBnm/'
  weight = -90
[[menu.main]]
  name = 'Blog'
  url = 'https://medium.com/perpdex'
  weight = -80
[[menu.main]]
  name = 'Contact Us'
  url = '#footer'
  weight = -70

[params]
  favicon = "https://fascinating-daffodil-abb5d2.netlify.app/images/perpdex_logo.png"
  custom_css = ["css/override.css"]
  site_logo = "images/perpdex_logo_header.svg"
