baseURL = 'https://perpdex.com/'
languageCode = 'en-us'
title = 'PerpDEX'
theme = "ananke"
relativeURLs = true

[menu]
[[menu.main]]
  name = 'Whitepaper'
  url = 'https://perpdex.com/pdfs/whitepaper.pdf'
  weight = -120
# [[menu.main]]
#   name = 'Litepaper'
#   url = 'https://magnetic-holiday-dbf.notion.site/PerpDEX-Litepaper-acac35286f214b6db60dc64e58f42ca2'
#   weight = -110
[[menu.main]]
  name = 'App (rinkeby testnet)'
  url = 'https://cloudflare-ipfs.com/ipfs/QmYLySzkqAQ9P4Kedu3TWBHxdFwdopD1YdBKimo2mSJBnm/'
  weight = -100

[params]
  favicon = "https://fascinating-daffodil-abb5d2.netlify.app/images/perpdex_logo.png"
